version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mi-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: autos
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mi-mysql          
      - PMA_PORT=3306
      - PMA_USER=root              
      - PMA_PASSWORD=
    depends_on:
      - mi-mysql
    restart: unless-stopped