# =============================================
#   NovaDrive Backend - Configuración
# =============================================

# Puerto del servidor (diferente al frontend :4200 y a phpmyadmin :8080)
server.port=8081

# ── Base de Datos MySQL / MariaDB (Docker) ───────────────────
# Ajusta puerto, nombre de bd (autos), usuario y password
#spring.datasource.url=jdbc:mysql://localhost:3306/autos?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.url=jdbc:mysql://localhost:3306/mi_basedatos?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=miClaveSegura123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Si usaste PostgreSQL en Docker, comenta las 4 líneas de MYSQL arriba y descomenta estas:
# spring.datasource.url=jdbc:postgresql://localhost:5432/autos
# spring.datasource.username=postgres
# spring.datasource.password=root
# spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA / Hibernate ──────────────────────────────────────────
# update: actualiza el esquema sin borrar los datos cada que inicias
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ── Nombre de la aplicación ──────────────────────────────────
spring.application.name=novadrive-backend

# ── Logging ──────────────────────────────────────────────────
logging.level.com.novadrive=DEBUG
logging.level.org.springframework.security=WARN
